# Generated by Django 5.0.2 on 2024-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_timesheet", "0002_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="date",
            field=models.DateField(),
        ),
    ]
