# Generated by Django 5.0.2 on 2024-02-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_timesheet", "0003_alter_master_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="master",
            old_name="emp_id",
            new_name="employee_id",
        ),
    ]
