# Generated by Django 5.0.2 on 2024-02-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_timesheet", "0004_rename_emp_id_master_employee_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="master",
            unique_together={("date", "employee_id")},
        ),
    ]
