# Generated by Django 5.0.2 on 2024-02-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_timesheet", "0005_alter_master_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
